apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid.v1
  namespace: tpts
  labels:
    team: tpts
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
    {{key}}: {{value}}
  {{/each}}
  acl:
    - team: tpts
      application: tiltakspenger-vedtak
      access: readwrite
