apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid.v1
  namespace: tpts
  labels:
    team: tpts
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
    {{key}}: {{value}}
  {{/each}}
  acl:
    - team: tpts
      application: tiltakspenger-vedtak
      access: readwrite
    - team: tpts
      application: tiltakspenger-mottak
      access: readwrite
    - team: tpts
      application: tiltakspenger-fakta-person
      access: readwrite
    - team: tpts
      application: tiltakspenger-fakta-institusjon
      access: readwrite
    - team: tpts
      application: tiltakspenger-arena
      access: readwrite
    - team: tpts
      application: tiltakspenger-skjerming
      access: readwrite
    - team: tpts
      application: tiltakspenger-testmeldinger
      access: readwrite
    - team: tpts
      application: tiltakspenger-fp
      access: readwrite
    - team: tpts
      application: tiltakspenger-ufore
      access: readwrite
