apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltakspenger-felles-alerts
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  groups:
    - name: tiltakspenger-felles-alerts
      rules:
        - alert: Applikasjon er nede
          expr: sum by (deployment) (kube_deployment_status_replicas_available{namespace="{{namespace}}"}) == 0
          for: 5m
          annotations:
            consequence: '\{{ $labels.deployment }} har utilgjengelige podder'
            action: '`kubectl describe pod -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for events og `kubectl get  pods -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for å se feilende podder'
          labels:
            namespace: {{namespace}}
            severity: critical
        - alert: Høy feilrate i logger (> 5 feil siste timen og > 0 feil siste 15 min)
          expr: max(sum_over_time(loki:service:loglevel:count1m{detected_level="error", service_namespace="{{namespace}}", k8s_container_name=~"tiltakspenger-.*"}[1h])) by (service_name) > 5 and max(sum_over_time(loki:service:loglevel:count1m{detected_level="error", service_namespace="{{namespace}}", k8s_container_name=~"tiltakspenger-.*"}[15m])) by (service_name) > 0
          annotations:
            action: "Sjekk loggene til appen \{{ $labels.service_name }} for å se hvorfor det er så mye feil"
            dashboard_url: 'https://grafana.nav.cloud.nais.io/a/grafana-lokiexplore-app/explore/service/{{ $labels.service_name }}/logs?var-filters=service_name%7C%3D%7C{{ $labels.service_name }}&var-filters=service_namespace%7C%3D%7C{{namespace}}&from=now-3h&to=now&var-levels=detected_level%7C%3D%7Cerror&var-ds={{datasource}}'
          labels:
            namespace: {{namespace}}
            severity: critical
            datasource: {{datasource}}
        - alert: Utbetaling har feilet
          expr: tpts_saksbehandlingapi_utbetaling_feilet_count_total > 0
          annotations:
            action: "Sjekk loggene til saksbehandling-api for å se hva som har skjedd"
          labels:
            namespace: {{namespace}}
            severity: critical
        - alert: Utbetaling har ikke gått ok etter 3 dager
          expr: tpts_saksbehandlingapi_utbetaling_ikke_ok_count_total > 0
          annotations:
            action: "Sjekk loggene til saksbehandling-api for å se hva som har skjedd"
          labels:
            namespace: {{namespace}}
            severity: critical
