apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltakspenger-felles-alerts
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  groups:
    - name: tiltakspenger-felles-alerts
      rules:
        - alert: Applikasjon er nede
          expr: sum by (deployment) (kube_deployment_status_replicas_available{namespace="{{namespace}}"}) == 0
          for: 5m
          annotations:
            consequence: '\{{ $labels.deployment }} har utilgjengelige podder'
            action: '`kubectl describe pod -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for events og `kubectl get  pods -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for å se feilende podder'
          labels:
            namespace: {{namespace}}
            severity: critical
        - alert: Høy feilrate i logger (> 10 feil siste timen)
          expr: sum by(app) (increase(log_messages_errors{namespace="{{namespace}}", level="Error"}[1h])) > 10
          for: 5m
          annotations:
            action: "Sjekk loggene til app \{{ $labels.app }} for å se hvorfor det er så mye feil"
          labels:
            namespace: {{namespace}}
            severity: critical
