apiVersion: nais.io/v1
kind: Alert
metadata:
  name: felles-alerts
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  receivers:
    slack:
      channel: '{{alerts_slack_channel}}'
      prependText: '<!here> | '
    email:
      to: 'per.jorgen.walstrom@nav.no'
      send_resolved: true
    sms:
      recipients: '97124040'
      send_resolved: false
  alerts:
    - alert: applikasjon nede
      expr: sum(kube_deployment_status_replicas_available{namespace="{{namespace}}"}) by (deployment, namespace) == 0
      for: 5m      
      description: '\{{ $labels.deployment }} har utilgjengelige podder i \{{ $labels.namespace }}'
      action: '`kubectl describe pod -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for events og `kubectl get  pods -l app=\{{ $labels.deployment }} -n \{{ $labels.namespace }}` for å se feilende podder (felles alert)'
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_level="Error", log_namespace="{{namespace}}"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_namespace="{{namespace}}"}[3m]))) > 90
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
    - alert: feil i selftest
      expr: selftests_aggregate_result_status{kubernetes_namespace="{{namespace}}"} > 0
      for: 1m
      action: "Sjekk app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt"
