apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: journalpostider.v1
  namespace: tpts
  labels:
    team: tpts
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
    {{key}}: {{value}}
  {{/each}}
  acl:
    - team: tpts
      application: tiltakspenger-saksbehandling-api
      access: readwrite
    - team: tpts
      application: tiltakspenger-arena
      access: read
    - team: tpts
      application: tiltakspenger-tiltak
      access: readwrite
