name: Deploy alerts

on:
  push:
    branches:
      - main
    paths:
      - alerts/**
      - .github/workflows/deploy-alerts.yaml

jobs:
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ dev-gcp, dev-fss ]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: alerts/felles-alerts.yaml
          VARS: alerts/.nais/vars.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [ prod-gcp, prod-fss ]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: alerts/felles-alerts.yaml
          VARS: alerts/.nais/vars.yaml
          PRINT_PAYLOAD: true
